name: "Infrastructure Setup Workflow"
description: "Complete workflow for setting up new infrastructure with deployment, monitoring, and security"
version: "1.0"
category: "operations"
tags: ["infrastructure", "deployment", "devops", "setup"]

metadata:
  complexity: "high"
  skillLevel: "advanced"

phases:
  - phase: "planning-clarification"
    description: "Infrastructure requirements and scope definition"
    required: true
    steps:
      - id: "gather-requirements"
        miniPrompt: "business/gather-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["infrastructure_budget", "compliance_requirements"]
        
      - id: "ask-clarifying-questions"
        miniPrompt: "development/ask-clarifying-questions"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_requirements"]
          optionalContext: ["existing_infrastructure"]
        dependencies: ["gather-requirements"]

  - phase: "analysis"
    description: "Infrastructure analysis and capacity planning"
    required: true
    steps:
      - id: "architecture-analysis"
        miniPrompt: "analysis/architecture-analysis"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_requirements", "target_architecture"]
          optionalContext: ["existing_infrastructure", "performance_requirements"]
        dependencies: ["ask-clarifying-questions"]

  - phase: "design-architecture"
    description: "Infrastructure architecture design and planning"
    required: true
    steps:
      - id: "design-architecture"
        miniPrompt: "development/design-architecture"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_analysis", "technical_requirements"]
          optionalContext: ["cloud_platform_choice", "security_requirements"]
        dependencies: ["architecture-analysis"]

  - phase: "implementation"
    description: "Infrastructure provisioning and configuration"
    required: true
    steps:
      - id: "configure-infrastructure"
        miniPrompt: "operations/configure-infrastructure"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_design", "target_environment"]
          optionalContext: ["infrastructure_as_code", "automation_tools"]
        dependencies: ["design-architecture"]
        
      - id: "manage-secrets"
        miniPrompt: "operations/manage-secrets"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_setup", "security_requirements"]
          optionalContext: ["secrets_management_platform", "compliance_needs"]
        dependencies: ["configure-infrastructure"]
        
      - id: "setup-cicd-pipeline"
        miniPrompt: "operations/setup-cicd-pipeline"
        required: false
        prerequisites:
          requiredContext: ["infrastructure_setup", "application_deployment_needs"]
          optionalContext: ["source_repository", "deployment_strategy"]
          skipConditions: ["infrastructure_only", "manual_deployment_preferred"]
        dependencies: ["configure-infrastructure"]

  - phase: "testing-validation"
    description: "Infrastructure testing and validation"
    required: true
    steps:
      - id: "create-test-plan"
        miniPrompt: "qa/create-test-plan"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_setup", "functional_requirements"]
          optionalContext: ["performance_benchmarks", "security_test_requirements"]
        dependencies: ["configure-infrastructure"]
        
      - id: "execute-tests"
        miniPrompt: "qa/execute-tests"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_test_plan", "configured_infrastructure"]
          optionalContext: ["load_testing_tools", "security_scanning_tools"]
        dependencies: ["create-test-plan"]

  - phase: "deployment-operations"
    description: "Monitoring and operational readiness"
    required: true
    steps:
      - id: "monitor-system-health"
        miniPrompt: "operations/monitor-system-health"
        required: true
        prerequisites:
          requiredContext: ["configured_infrastructure"]
          optionalContext: ["monitoring_requirements", "alerting_preferences"]
        dependencies: ["execute-tests"]
        
      - id: "backup-recovery"
        miniPrompt: "operations/backup-recovery"
        required: true
        prerequisites:
          requiredContext: ["infrastructure_setup", "data_protection_requirements"]
          optionalContext: ["compliance_backup_needs", "disaster_recovery_plan"]
        dependencies: ["execute-tests"]

  - phase: "completion-reflection"
    description: "Documentation and knowledge transfer"
    required: true
    steps:
      - id: "document-decisions"
        miniPrompt: "business/document-decisions"
        required: true
        prerequisites:
          requiredContext: ["completed_infrastructure"]
          optionalContext: ["architectural_decisions", "operational_procedures"]
        dependencies: ["monitor-system-health", "backup-recovery"] 