name: "TRD Creation Workflow"
description: "Create comprehensive Technical Requirements Document from feature ideas or business requirements"
version: "1.0"
category: "documentation"
tags: ["trd", "documentation", "technical-requirements", "planning"]

metadata:
  complexity: "medium"
  skillLevel: "intermediate"

phases:
  - phase: "planning-clarification"
    description: "Requirements gathering and scope definition"
    required: true
    steps:
      - id: "gather-requirements"
        miniPrompt: "business/gather-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["existing_feature_description", "business_requirements"]
        
      - id: "ask-clarifying-questions"
        miniPrompt: "development/ask-clarifying-questions"
        required: true
        prerequisites:
          requiredContext: ["requirements"]
          optionalContext: ["stakeholder_contact_info", "business_context"]
        dependencies: ["gather-requirements"]

  - phase: "analysis"
    description: "Technical analysis and architecture planning"
    required: true
    steps:
      - id: "feature-analysis"
        miniPrompt: "analysis/feature-analysis"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements"]
          optionalContext: ["existing_codebase", "system_architecture"]
        dependencies: ["ask-clarifying-questions"]
        
      - id: "architecture-analysis"
        miniPrompt: "analysis/architecture-analysis"
        required: false
        prerequisites:
          requiredContext: ["system_architecture"]
          optionalContext: ["performance_requirements", "scalability_needs"]
          skipConditions: ["simple_feature", "no_architecture_impact"]

  - phase: "design-architecture"
    description: "Solution design and technical specification"
    required: true
    steps:
      - id: "design-architecture"
        miniPrompt: "development/design-architecture"
        required: true
        prerequisites:
          requiredContext: ["feature_analysis", "technical_requirements"]
          optionalContext: ["architecture_analysis", "existing_patterns"]
        dependencies: ["feature-analysis"]

  - phase: "completion-reflection"
    description: "Documentation creation and validation"
    required: true
    steps:
      - id: "create-trd"
        miniPrompt: "business/create-trd"
        required: true
        prerequisites:
          requiredContext: ["design_specifications", "technical_analysis"]
          optionalContext: ["architectural_decisions", "trade_off_analysis"]
        dependencies: ["design-architecture"]
        
      - id: "stakeholder-approval"
        miniPrompt: "business/stakeholder-approval"
        required: false
        prerequisites:
          requiredContext: ["completed_trd", "documentation"]
          optionalContext: ["stakeholder_feedback"]
          skipConditions: ["internal_project", "no_formal_approval_needed"]
        dependencies: ["document-decisions"]

# Workflow-level configurations
skipConditions:
  - condition: "trd_already_exists"
    message: "TRD documentation already exists and is up to date"
  - condition: "requirements_unclear"
    message: "Requirements are too vague to create meaningful technical documentation"

validationRules:
  - rule: "technical_clarity_required"
    phases: ["design-architecture"]
    message: "Technical specifications must be clear and implementable"
  - rule: "documentation_completeness"
    phases: ["completion-reflection"]
    dependencies: ["design-architecture"]
    message: "All technical decisions must be documented before completion"

notifications:
  - trigger: "phase_completion"
    phases: ["analysis", "design-architecture"]
    message: "Phase completed, technical analysis ready for next phase"
  - trigger: "workflow_completion"
    message: "TRD creation workflow completed successfully"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  parallelExecution: false
  automaticProgressTracking: true
  
# Integration settings
integrations:
  documentation:
    - confluence
    - notion
    - github-wiki
  projectManagement:
    - jira
    - asana
    - linear 