name: "Code Refactoring Workflow"
description: "Systematic code refactoring to improve architecture, performance, and maintainability"
version: "1.0"
category: "development"
tags: ["refactoring", "architecture", "performance", "maintainability", "technical-debt"]

phases:
  - phase: "planning-clarification"
    description: "Requirements gathering and refactoring scope definition - CRITICAL: Ask detailed clarifying questions to fully understand refactoring goals and constraints before proceeding"
    required: true
    steps:
      - id: "create-structured-requirements"
        miniPrompt: "business/create-structured-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["existing_codebase", "performance_issues", "maintenance_concerns", "technical_debt", "user_personas", "business_context", "refactoring_scope"]
        outputs: ["structured_requirements", "user_stories", "acceptance_criteria"]
        
      - id: "handoff-to-analysis"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements"]
          optionalContext: []
        dependencies: ["create-structured-requirements"]

  - phase: "analysis-design"
    description: "Code analysis and refactoring strategy design"
    required: true
    steps:
      - id: "code-analysis"
        miniPrompt: "analysis/code-analysis"
        required: true
        prerequisites:
          requiredContext: ["existing_codebase", "structured_requirements"]
          optionalContext: ["performance_metrics", "maintenance_issues"]
        dependencies: ["handoff-to-analysis"]
        
      - id: "handoff-to-planning"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["code_analysis_results"]
          optionalContext: []
        dependencies: ["code-analysis"]
        
  - phase: "implementation-planning"
    description: "Technical planning and implementation strategy"
    required: true
    steps:
      - id: "create-implementation-plan"
        miniPrompt: "business/create-implementation-plan"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements", "code_analysis_results"]
          optionalContext: ["technical_architecture", "development_environment", "team_capabilities", "existing_codebase"]
        dependencies: ["handoff-to-planning"]
        outputs: ["implementation_plan", "task_breakdown", "technical_specifications"]
        
      - id: "handoff-to-implementation"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["implementation_plan"]
          optionalContext: []
        dependencies: ["create-implementation-plan"]

  - phase: "implementation"
    description: "Code refactoring execution"
    required: true
    steps:
      - id: "implement-feature"
        miniPrompt: "development/implement-feature"
        required: true
        prerequisites:
          requiredContext: ["implementation_plan", "code_analysis_results"]
          optionalContext: ["migration_strategy", "backward_compatibility", "existing_codebase"]
        dependencies: ["handoff-to-implementation"]
        
      - id: "handoff-to-validation"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["refactored_code"]
          optionalContext: []
        dependencies: ["implement-feature"]

  - phase: "validation"
    description: "Testing and refactoring validation"
    required: true
    steps:
      - id: "execute-tests"
        miniPrompt: "qa/execute-tests"
        required: true
        prerequisites:
          requiredContext: ["refactored_code", "original_functionality"]
          optionalContext: ["automated_tests", "performance_benchmarks", "test_plan"]
        dependencies: ["handoff-to-validation"]

# Workflow-level configurations
skipConditions:
  - condition: "new_greenfield_project"
    message: "No existing code to refactor, use feature-development workflow instead"
  - condition: "minimal_technical_debt"
    message: "Codebase doesn't require significant refactoring"

validationRules:
  - rule: "requirements_validation_required"
    phases: ["planning-clarification"]
    message: "Refactoring requirements and scope must be clearly defined before proceeding to analysis"
  - rule: "backward_compatibility_required"
    phases: ["implementation"]
    dependencies: ["analysis-design"]
    message: "Refactoring must maintain backward compatibility unless technical requirements specify otherwise"
  - rule: "performance_validation_required"
    phases: ["validation"]
    dependencies: ["implementation"]
    message: "Performance impact must be measured and validated"

notifications:
  - trigger: "phase_completion"
    phases: ["planning-clarification", "analysis-design", "implementation"]
    message: "Major refactoring phase completed"
  - trigger: "workflow_completion"
    message: "Code refactoring completed successfully"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true 