name: "Feature Development Workflow"
description: "Complete workflow for implementing and developing new features, improvements, and enhancements from requirements to deployment"
version: "1.0"
category: "development"
tags: ["feature", "development", "implementation", "enhancement", "improvement", "build", "create", "full-cycle"]

phases:
  - phase: "planning-clarification"
    description: "Requirements gathering, clarification and scope definition"
    required: true
    steps:
      - id: "gather-and-clarify-requirements"
        miniPrompt: "business/gather-and-clarify-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["product_roadmap", "user_feedback"]
        
      - id: "create-structured-requirements"
        miniPrompt: "business/create-structured-requirements"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements"]
          optionalContext: ["user_personas", "business_context"]
        dependencies: ["gather-and-clarify-requirements"]
        outputs: ["structured_requirements", "user_stories", "acceptance_criteria"]
        
      - id: "create-implementation-plan"
        miniPrompt: "business/create-implementation-plan"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements", "clarified_requirements"]
          optionalContext: ["technical_architecture", "development_environment", "team_capabilities"]
        dependencies: ["create-structured-requirements"]
        outputs: ["implementation_plan", "task_breakdown", "technical_specifications"]
        
      - id: "handoff-to-design"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements", "structured_requirements", "implementation_plan"]
          optionalContext: []
        dependencies: ["create-implementation-plan"]

  - phase: "design-architecture"
    description: "Technical design and architecture specification"
    required: true
    iterative: true
    steps:
      - id: "create-trd-with-design"
        miniPrompt: "business/create-trd"
        required: true
        iterative: true
        prerequisites:
          requiredContext: ["clarified_requirements", "structured_requirements", "implementation_plan"]
          optionalContext: ["technical_decisions", "existing_patterns", "development_environment", "existing_codebase"]
        dependencies: ["handoff-to-design"]
        outputs: ["design_specifications", "technical_requirements", "architecture_specifications"]
        
      - id: "handoff-to-implementation"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["design_specifications", "implementation_plan"]
          optionalContext: []
        dependencies: ["create-trd-with-design"]

  - phase: "implementation"
    description: "Technical execution and coding with iterative improvements"
    required: true
    steps:
      - id: "implement-feature"
        miniPrompt: "development/implement-feature"
        required: true
        prerequisites:
          requiredContext: ["design_specifications", "implementation_plan"]
          optionalContext: ["development_environment", "coding_standards", "review_feedback"]
        dependencies: ["handoff-to-implementation"]
        
      - id: "write-unit-tests"
        miniPrompt: "qa/write-unit-tests"
        required: true
        prerequisites:
          requiredContext: ["implemented_feature"]
          optionalContext: ["test_framework", "testing_standards"]
        dependencies: ["implement-feature"]
        
      - id: "handoff-to-review"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["implemented_feature", "unit_tests"]
          optionalContext: []
        dependencies: ["write-unit-tests"]

  - phase: "review"
    description: "CRITICAL and thorough assessment of code quality, security, and production readiness with feedback loop"
    required: true
    iterative: true
    steps:
      - id: "code-review"
        miniPrompt: "review/code-review"
        required: true
        prerequisites:
          requiredContext: ["implemented_feature", "unit_tests"]
          optionalContext: ["code_review_checklist", "quality_standards"]
        dependencies: ["handoff-to-review"]
        
      - id: "bugfix-handoff"
        miniPrompt: "handoff-memory-board"
        required: false
        conditional: true
        condition: "bugs_or_issues_found"
        prerequisites:
          requiredContext: ["review_feedback", "issues_identified"]
          optionalContext: []
        dependencies: ["code-review"]
        loopback:
          targetPhase: "implementation"
          targetStep: "implement-feature"
          context: ["review_feedback", "bugs_to_fix"]
         
      - id: "handoff-to-testing"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["reviewed_feature", "code_review_results"]
          optionalContext: []
        dependencies: ["code-review"]
        skipConditions: ["bugs_or_issues_found"]

  - phase: "testing-validation"
    description: "Quality assurance and validation"
    required: true
    steps:
      - id: "create-test-plan"
        miniPrompt: "qa/create-test-plan"
        required: true
        prerequisites:
          requiredContext: ["feature_specifications", "reviewed_feature"]
          optionalContext: ["testing_framework", "test_data"]
        dependencies: ["handoff-to-testing"]
        
      - id: "execute-tests"
        miniPrompt: "qa/execute-tests"
        required: true
        prerequisites:
          requiredContext: ["test_plan", "reviewed_feature"]
          optionalContext: ["test_automation", "test_environments"]
        dependencies: ["create-test-plan"]
        




# Workflow-level configurations
skipConditions:
  - condition: "feature_already_implemented"
    message: "Feature has already been implemented and deployed"
  - condition: "requirements_incomplete"
    message: "Feature requirements are incomplete or unclear"
  - condition: "bugs_or_issues_found"
    message: "Issues found during review, looping back to implementation"

validationRules:
  - rule: "requirements_validation_required"
    phases: ["planning-clarification"]
    message: "Requirements validation required before proceeding to implementation"
  - rule: "unit_tests_required"
    phases: ["implementation"]
    message: "Unit tests must be written after feature implementation"
  - rule: "review_feedback_loop"
    phases: ["review"]
    message: "Review phase must complete successfully or provide feedback for bugfixes"


notifications:
  - trigger: "phase_completion"
    phases: ["implementation", "review", "testing-validation"]
    message: "Phase completed, ready for next phase"
  - trigger: "workflow_completion"
    message: "Feature development workflow completed successfully"
  - trigger: "bugfix_loop"
    phases: ["review"]
    condition: "bugs_or_issues_found"
    message: "Issues found during review, returning to implementation for bugfixes"
  - trigger: "unit_tests_completed"
    phases: ["implementation"]
    message: "Unit tests written and ready for review"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true
  allowIterativeLoops: true
  maxIterations: 3
  loopbackSupport: true 