name: "Feature Development Workflow"
description: "Complete workflow for implementing and developing new features, improvements, and enhancements from requirements to deployment"
version: "1.0"
category: "development"
tags: ["feature", "development", "implementation", "enhancement", "improvement", "build", "create", "full-cycle"]

phases:
  - phase: "planning-clarification"
    description: "Requirements gathering and scope definition"
    required: true
    steps:
      - id: "create-structured-requirements"
        miniPrompt: "business/create-structured-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["product_roadmap", "user_feedback", "user_personas", "business_context"]
        outputs: ["structured_requirements", "user_stories", "acceptance_criteria"]

  - phase: "design-architecture"
    description: "Technical design and architecture specification"
    required: true
    steps:
      - id: "create-trd"
        miniPrompt: "business/create-trd"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements"]
          optionalContext: ["technical_decisions", "existing_patterns", "development_environment", "existing_codebase"]
        outputs: ["design_specifications", "technical_requirements", "architecture_specifications"]
        
  - phase: "implementation-planning"
    description: "Technical planning and implementation strategy"
    required: true
    steps:
      - id: "create-implementation-plan"
        miniPrompt: "business/create-implementation-plan"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements", "design_specifications"]
          optionalContext: ["technical_architecture", "development_environment", "team_capabilities"]
        outputs: ["implementation_plan", "task_breakdown", "technical_specifications"]

  - phase: "implementation"
    description: "Technical execution and coding"
    required: true
    steps:
      - id: "implement-feature"
        miniPrompt: "development/implement-feature"
        required: true
        prerequisites:
          requiredContext: ["design_specifications", "implementation_plan"]
          optionalContext: ["development_environment", "coding_standards"]

  - phase: "testing-validation"
    description: "Quality assurance and validation"
    required: true
    steps:
      - id: "execute-tests"
        miniPrompt: "qa/execute-tests"
        required: true
        prerequisites:
          requiredContext: ["implemented_feature"]
          optionalContext: ["test_automation", "test_environments", "test_plan"]

# Workflow-level configurations
skipConditions:
  - condition: "feature_already_implemented"
    message: "Feature has already been implemented and deployed"
  - condition: "requirements_incomplete"
    message: "Feature requirements are incomplete or unclear"

validationRules:
  - rule: "requirements_validation_required"
    phases: ["planning-clarification"]
    message: "Requirements validation required before proceeding to design"

notifications:
  - trigger: "phase_completion"
    phases: ["planning-clarification", "design-architecture", "implementation-planning", "implementation", "testing-validation"]
    message: "Phase completed, ready for next phase"
  - trigger: "workflow_completion"
    message: "Feature development workflow completed successfully"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true 