name: "Feature Development Workflow"
description: "Complete workflow for implementing and developing new features, improvements, and enhancements from requirements to deployment"
version: "1.0"
category: "development"
tags: ["feature", "development", "implementation", "enhancement", "improvement", "build", "create", "full-cycle"]

# CRITICAL: VALIDATE ALL STEPS BEFORE STARTING
agentInstructions:
  validation:
    required: true
    message: "🚨 MANDATORY: Before starting, validate ALL workflow steps, prerequisites, mini-prompts access, and required context. Execute ALL steps completely - no skipping unless explicitly optional."

phases:
  - phase: "analysis"
    description: "Requirements gathering and scope definition - CRITICAL: Ask detailed clarifying questions to fully understand the task before proceeding"
    required: true
    steps:
      - id: "create-structured-requirements"
        miniPrompt: "analysis/create-structured-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["product_roadmap", "user_feedback", "user_personas", "business_context"]
        outputs: ["structured_requirements", "user_stories", "acceptance_criteria"]
        
      - id: "handoff-to-design"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements"]
          optionalContext: []
        dependencies: ["create-structured-requirements"]

  - phase: "design-architecture"
    description: "Technical design and architecture specification"
    required: true
    steps:
      - id: "design-architecture"
        miniPrompt: "design-architecture/design-architecture"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements", "structured_requirements"]
          optionalContext: ["design_guidelines", "technical_constraints"]
        dependencies: ["handoff-to-design"]
        outputs: ["design_specifications", "technical_requirements", "architecture_specifications"]
        
      - id: "handoff-to-planning"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["design_specifications"]
          optionalContext: []
        dependencies: ["design-architecture"]

  - phase: "planning"
    description: "Implementation planning and strategy"
    required: true
    steps:
      - id: "create-implementation-plan"
        miniPrompt: "planning/create-implementation-plan"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements", "design_specifications"]
          optionalContext: ["technical_architecture", "development_environment", "team_capabilities"]
        dependencies: ["handoff-to-planning"]
        outputs: ["implementation_plan", "task_breakdown", "technical_specifications"]
        
      - id: "handoff-to-implementation"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["implementation_plan"]
          optionalContext: []
        dependencies: ["create-implementation-plan"]

  - phase: "implementation"
    description: "Technical execution and coding"
    required: true
    steps:
      - id: "implement-feature"
        miniPrompt: "implementation/implement-feature"
        required: true
        prerequisites:
          requiredContext: ["design_specifications", "implementation_plan"]
          optionalContext: ["development_environment", "coding_standards"]
        dependencies: ["handoff-to-implementation"]
        
      - id: "handoff-to-testing"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["implemented_feature"]
          optionalContext: []
        dependencies: ["implement-feature"]

  - phase: "testing-review"
    description: "Quality assurance, testing, and validation"
    required: true
    steps:
      - id: "execute-tests"
        miniPrompt: "testing-review/execute-tests"
        required: true
        prerequisites:
          requiredContext: ["implemented_feature"]
          optionalContext: ["test_automation", "test_environments", "test_plan"]
        dependencies: ["handoff-to-testing"]
        

# Workflow-level configurations
skipConditions:
  - condition: "feature_already_implemented"
    message: "Feature has already been implemented and deployed"
  - condition: "requirements_incomplete"
    message: "Feature requirements are incomplete or unclear"

validationRules:
  - rule: "requirements_validation_required"
    phases: ["analysis"]
    message: "Requirements validation required before proceeding to design"

notifications:
  - trigger: "phase_completion"
    phases: ["analysis", "design-architecture", "planning", "implementation", "testing-review"]
    message: "Phase completed, ready for next phase"
  - trigger: "workflow_completion"
    message: "Feature development workflow completed successfully"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true 