name: "Product Development Workflow"
description: "Comprehensive product development from idea to launch including planning, development, and validation"
version: "1.0"
category: "development"
tags: ["product", "development", "planning", "full-cycle", "launch"]

phases:
  - phase: "planning-clarification"
    description: "Product planning and requirements definition"
    required: true
    steps:
      - id: "gather-requirements"
        miniPrompt: "business/gather-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["existing_feature_analysis"]
        
      - id: "ask-clarifying-questions"
        miniPrompt: "development/ask-clarifying-questions"
        required: true
        prerequisites:
          requiredContext: ["requirements"]
          optionalContext: []
        dependencies: ["gather-requirements"]
        
      - id: "handoff-to-analysis"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements"]
          optionalContext: []
        dependencies: ["ask-clarifying-questions"]

  - phase: "analysis"
    description: "Market and technical analysis"
    required: true
    steps:
      - id: "feature-analysis"
        miniPrompt: "analysis/feature-analysis"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements", "product_vision"]
          optionalContext: ["existing_analysis"]
        dependencies: ["handoff-to-analysis"]
        
      - id: "architecture-analysis"
        miniPrompt: "analysis/architecture-analysis"
        required: true
        prerequisites:
          requiredContext: ["feature_analysis", "technical_requirements"]
          optionalContext: ["scalability_requirements", "performance_targets"]
        dependencies: ["feature-analysis"]
        
      - id: "handoff-to-design"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["feature_analysis", "architecture_analysis"]
          optionalContext: []
        dependencies: ["architecture-analysis"]

  - phase: "design-architecture"
    description: "Product and technical design"
    required: true
    steps:
      - id: "design-architecture"
        miniPrompt: "development/design-architecture"
        required: true
        prerequisites:
          requiredContext: ["feature_analysis", "architecture_analysis"]
          optionalContext: ["design_guidelines", "technical_constraints"]
        dependencies: ["handoff-to-design"]
        
      - id: "handoff-to-implementation"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["design_specifications"]
          optionalContext: []
        dependencies: ["design-architecture"]

  - phase: "implementation"
    description: "Product development and implementation"
    required: true
    steps:
      - id: "implement-feature"
        miniPrompt: "development/implement-feature"
        required: true
        prerequisites:
          requiredContext: ["design_specifications", "technical_architecture"]
          optionalContext: ["development_environment", "coding_standards"]
        dependencies: ["handoff-to-implementation"]
        
      - id: "handoff-to-testing"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["implemented_features"]
          optionalContext: []
        dependencies: ["implement-feature"]

  - phase: "testing-validation"
    description: "Quality assurance and user validation"
    required: true
    steps:
      - id: "create-test-plan"
        miniPrompt: "qa/create-test-plan"
        required: true
        prerequisites:
          requiredContext: ["implemented_features", "product_requirements"]
          optionalContext: ["acceptance_criteria"]
        dependencies: ["handoff-to-testing"]
        
      - id: "execute-tests"
        miniPrompt: "qa/execute-tests"
        required: true
        prerequisites:
          requiredContext: ["test_plan", "implemented_features"]
          optionalContext: ["test_automation"]
        dependencies: ["create-test-plan"]
        
      - id: "handoff-to-review"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["test_results", "validated_features"]
          optionalContext: []
        dependencies: ["execute-tests"]

  - phase: "review"
    description: "Product quality assessment and validation"
    required: true
    steps:
      - id: "deliverable-review"
        miniPrompt: "review/deliverable-review"
        required: true
        prerequisites:
          requiredContext: ["implemented_features", "test_results", "product_requirements"]
          optionalContext: ["user_feedback"]
        dependencies: ["handoff-to-review"]
        



# Workflow-level configurations
skipConditions:
  - condition: "product_already_launched"
    message: "Product has already been successfully launched"
  - condition: "insufficient_technical_requirements"
    message: "Insufficient technical requirements for full product development"

validationRules:
  - rule: "requirements_validation_required"
    phases: ["analysis"]
    message: "Requirements validation required before development"
  - rule: "feature_testing_required"
    phases: ["testing-validation"]
    dependencies: ["implementation"]
    message: "Feature testing must be completed before launch"
  - rule: "performance_validation_required"
    phases: ["review"]
    dependencies: ["testing-validation"]
    message: "Performance testing required before review completion"

notifications:
  - trigger: "phase_completion"
    phases: ["analysis", "implementation", "testing-validation", "review"]
    message: "Major phase completed, ready for next milestone"
  - trigger: "workflow_completion"
    message: "Product development workflow completed successfully"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true 