name: "Product/Feature PRD Planning"
description: "Plan and assemble a PRD for products or big features with requirements, design, features, and a final index"
version: "1.0"
category: "product-feature"
tags: ["prd", "planning", "requirements", "design", "features", "product", "big-feature", "documentation"]

# CRITICAL: VALIDATE ALL STEPS BEFORE STARTING
agentInstructions:
  validation:
    required: true
    message: "🚨 MANDATORY: Before starting, validate ALL workflow steps, prerequisites, mini-prompts access, and required context. Execute ALL steps completely - no skipping unless explicitly optional."

phases:
  - phase: "requirements"
    description: "Gather and structure high-level product/feature requirements"
    required: true
    steps:
      - id: "write-requirements-file"
        miniPrompt: "documentation/prd/write-requirements-file"
        required: true
        prerequisites:
          requiredContext: ["project_slug", "project_name"]
          optionalContext: ["project_summary", "stakeholders", "personas", "business_context", "scope_level"]
        outputs: ["requirements_file_path", "structured_requirements"]

  - phase: "design-architecture"
    description: "Define overall design architecture (framework, language, methodology, design system)"
    required: true
    steps:
      - id: "write-design-file"
        miniPrompt: "documentation/prd/write-design-file"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements", "project_slug"]
          optionalContext: ["technical_constraints", "technology_preferences"]
        dependencies: ["write-requirements-file"]
        outputs: ["design_file_path", "design_specifications"]
        
      - id: "write-design-system"
        miniPrompt: "documentation/prd/write-design-system"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements", "project_slug"]
          optionalContext: ["design_specifications", "brand_guidelines"]
        dependencies: ["write-design-file"]
        outputs: ["design_system_file_path", "design_system_specifications"]

  - phase: "planning"
    description: "Split into phases and features, create feature files"
    required: true
    steps:
      - id: "write-feature-file"
        miniPrompt: "documentation/prd/write-feature-file"
        required: true
        prerequisites:
          requiredContext: ["structured_requirements", "design_specifications", "project_slug"]
          optionalContext: ["design_system_specifications", "phase_breakdown"]
        dependencies: ["write-design-system"]
        outputs: ["feature_files", "feature_list"]

  - phase: "finalization"
    description: "Assemble final PRD with links to all created files"
    required: true
    steps:
      - id: "assemble-prd"
        miniPrompt: "documentation/prd/assemble-prd"
        required: true
        prerequisites:
          requiredContext: ["project_slug", "requirements_file_path", "design_file_path", "feature_files"]
          optionalContext: ["project_name", "project_summary", "design_system_file_path"]
        dependencies: ["write-feature-file"]
        outputs: ["prd_index_file_path"]

# Workflow-level configurations
skipConditions:
  - condition: "prd_already_exists"
    message: "PRD has already been created for this product/feature"
  - condition: "incomplete_project_context"
    message: "Project slug and name are required to generate PRD"

validationRules:
  - rule: "project_context_required"
    phases: ["requirements"]
    message: "Project slug and name must be provided before starting (use product or feature identifiers)"

notifications:
  - trigger: "phase_completion"
    phases: ["requirements", "design-architecture", "planning", "finalization"]
    message: "Phase completed, ready for next phase"
  - trigger: "workflow_completion"
    message: "Product/Feature PRD planning workflow completed successfully"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true

