name: "Quick Fix Workflow"
description: "Fast resolution for bugs, hotfixes, and small feature requests with minimal overhead"
version: "1.0"
category: "development"
tags: ["quick-fix", "hotfix", "bug", "urgent", "minimal"]

# CRITICAL: VALIDATE ALL STEPS BEFORE STARTING
agentInstructions:
  validation:
    required: true
    message: "🚨 MANDATORY: Before starting, validate ALL workflow steps, prerequisites, mini-prompts access, and required context. Execute ALL steps completely - no skipping unless explicitly optional."

phases:
  - phase: "analysis"
    description: "Requirements gathering and problem analysis - CRITICAL: Ask clarifying questions about the issue and desired outcome before implementing fix"
    required: true
    steps:
      - id: "ask-clarifying-questions"
        miniPrompt: "analysis/ask-clarifying-questions"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["issue_description", "error_logs", "reproduction_steps"]
          
      - id: "trace-bug-root-cause"
        miniPrompt: "analysis/trace-bug-root-cause"
        required: false
        prerequisites:
          requiredContext: ["bug_symptoms", "reproduction_steps"]
          optionalContext: ["error_logs", "system_logs"]
          skipConditions: ["obvious_fix", "simple_feature_request"]
        dependencies: ["ask-clarifying-questions"]

  - phase: "implementation"
    description: "Quick fix implementation"
    required: true
    steps:
      - id: "implement-feature"
        miniPrompt: "implementation/implement-feature"
        required: true
        prerequisites:
          requiredContext: ["problem_analysis", "solution_approach"]
          optionalContext: ["existing_code_context"]
        dependencies: ["ask-clarifying-questions"]
        
      - id: "handoff-to-testing"
        miniPrompt: "handoff-memory-board"
        required: false
        prerequisites:
          requiredContext: ["implemented_fix"]
          optionalContext: []
        dependencies: ["implement-feature"]
        skipConditions: ["trivial_change", "emergency_hotfix"]

  - phase: "testing-review"
    description: "Quick validation, testing, and quality assessment"
    required: false
    steps:
      - id: "execute-tests"
        miniPrompt: "testing-review/execute-tests"
        required: false
        prerequisites:
          requiredContext: ["implemented_fix"]
          optionalContext: ["test_cases", "reproduction_environment"]
          skipConditions: ["trivial_change", "emergency_hotfix"]
        dependencies: ["handoff-to-testing"]

# Workflow-level configurations
skipConditions:
  - condition: "complex_architecture_change"
    message: "Issue requires complex architectural changes, use feature-development workflow instead"
  - condition: "complex_approval_process"
    message: "Change requires extensive validation process, not suitable for quick fix"

validationRules:
  - rule: "minimal_scope_required"
    phases: ["analysis"]
    message: "Quick fixes must have minimal scope and impact"
  - rule: "low_risk_validation"
    phases: ["implementation"]
    dependencies: ["analysis"]
    message: "Changes must be low-risk and easily reversible"

notifications:
  - trigger: "workflow_completion"
    message: "Quick fix completed successfully"
  - trigger: "scope_expansion"
    message: "Scope expanding beyond quick fix, consider switching workflows"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true 