name: "TRD Creation Workflow"
description: "Create comprehensive Technical Requirements Document from feature ideas or business requirements"
version: "1.0"
category: "documentation"
tags: ["trd", "documentation", "technical-requirements", "planning"]

phases:
  - phase: "planning-clarification"
    description: "Requirements gathering and scope definition"
    required: true
    steps:
      - id: "gather-requirements"
        miniPrompt: "business/gather-requirements"
        required: true
        prerequisites:
          requiredContext: []
          optionalContext: ["existing_feature_description", "business_requirements"]
        
      - id: "ask-clarifying-questions"
        miniPrompt: "development/ask-clarifying-questions"
        required: true
        prerequisites:
          requiredContext: ["requirements"]
          optionalContext: ["business_context"]
        dependencies: ["gather-requirements"]
        
      - id: "handoff-to-analysis"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements"]
          optionalContext: []
        dependencies: ["ask-clarifying-questions"]

  - phase: "analysis"
    description: "Technical analysis and architecture planning"
    required: true
    steps:
      - id: "feature-analysis"
        miniPrompt: "analysis/feature-analysis"
        required: true
        prerequisites:
          requiredContext: ["clarified_requirements"]
          optionalContext: ["existing_codebase", "system_architecture"]
        dependencies: ["handoff-to-analysis"]
        
      - id: "architecture-analysis"
        miniPrompt: "analysis/architecture-analysis"
        required: false
        prerequisites:
          requiredContext: ["system_architecture"]
          optionalContext: ["performance_requirements", "scalability_needs"]
          skipConditions: ["simple_feature", "no_architecture_impact"]
          
      - id: "handoff-to-design"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["feature_analysis"]
          optionalContext: ["architecture_analysis"]
        dependencies: ["feature-analysis"]

  - phase: "design-architecture"
    description: "Solution design and technical specification"
    required: true
    steps:
      - id: "design-architecture"
        miniPrompt: "development/design-architecture"
        required: true
        prerequisites:
          requiredContext: ["feature_analysis", "technical_requirements"]
          optionalContext: ["architecture_analysis", "existing_patterns"]
        dependencies: ["handoff-to-design"]
        
      - id: "handoff-to-documentation"
        miniPrompt: "handoff-memory-board"
        required: true
        prerequisites:
          requiredContext: ["design_specifications"]
          optionalContext: []
        dependencies: ["trd-review"]

  - phase: "review"
    description: "TRD quality assessment and validation"
    required: true
    steps:
      - id: "trd-review"
        miniPrompt: "review/trd-review"
        required: true
        prerequisites:
          requiredContext: ["design_specifications", "technical_analysis"]
          optionalContext: ["original_requirements"]
        dependencies: ["handoff-to-documentation"]

# Workflow-level configurations
skipConditions:
  - condition: "trd_already_exists"
    message: "TRD documentation already exists and is up to date"
  - condition: "requirements_unclear"
    message: "Requirements are too vague to create meaningful technical documentation"

validationRules:
  - rule: "technical_clarity_required"
    phases: ["design-architecture"]
    message: "Technical specifications must be clear and implementable"
  - rule: "documentation_completeness"
    phases: ["review"]
    dependencies: ["design-architecture"]
    message: "All technical decisions must be documented before completion"

notifications:
  - trigger: "phase_completion"
    phases: ["analysis", "design-architecture"]
    message: "Phase completed, technical analysis ready for next phase"
  - trigger: "workflow_completion"
    message: "TRD creation workflow completed successfully"

# Smart execution settings
execution:
  allowSkipping: true
  requireExplicitApproval: false
  automaticProgressTracking: true 